import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Antonio
 */

class Node extends DefaultMutableTreeNode{
    JButton icon;
    boolean isFolder;
    String name;
    Node(String name, boolean isFolder){
        super(name);
        this.name = name;
        this.isFolder = isFolder;
        icon = new JButton(name);
        //icon.setBackground(new java.awt.Color(255, 255, 255));
        icon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        icon.setForeground(new java.awt.Color(102, 102, 102));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file.png"))); // NOI18N
        icon.setText(name);
        icon.setBorder(null);
        icon.setFocusPainted(false);
        icon.setFocusable(false);
        icon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icon.setOpaque(false);    
    }
}

public class UserInterface extends javax.swing.JFrame {
    
    Node raiz;
    Node actual_node;
    ImageIcon btIfolderplus;
    ImageIcon btIfolder;
    ImageIcon btIfile;
    CEnvia socket_salida = new CEnvia();
    
    public UserInterface() {
        Image img= new ImageIcon(getClass().getResource("/img/bt1.PNG")).getImage();
        ImageIcon btIcon1=new ImageIcon(img.getScaledInstance(45, 45, Image.SCALE_SMOOTH));
        img= new ImageIcon(getClass().getResource("/img/bt2.PNG")).getImage();
        ImageIcon btIcon2=new ImageIcon(img.getScaledInstance(45, 45, Image.SCALE_SMOOTH));
        img= new ImageIcon(getClass().getResource("/img/folderplus.PNG")).getImage();
        btIfolderplus=new ImageIcon(img.getScaledInstance(45, 45, Image.SCALE_SMOOTH));
        img= new ImageIcon(getClass().getResource("/img/folder.PNG")).getImage();
        btIfolder=new ImageIcon(img.getScaledInstance(45, 45, Image.SCALE_SMOOTH));
        img= new ImageIcon(getClass().getResource("/img/file.PNG")).getImage();
        btIfile=new ImageIcon(img.getScaledInstance(45, 45, Image.SCALE_SMOOTH));
        
        initComponents();
        
        
        bt_add.setIcon(btIcon1);
        bt_Folder.setIcon(btIfolderplus);
        //bt_File.setIcon(btIfile);
        raiz = new Node("Drive",true);
        file_tree.setModel(new DefaultTreeModel(raiz));
        actual_node = raiz;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        file_tree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_drive = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_Folder = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        file_tree.setForeground(new java.awt.Color(204, 204, 204));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("colors");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("sports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("food");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hot dogs");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pizza");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ravioli");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bananas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        file_tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(file_tree);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panel_drive.setBackground(new java.awt.Color(255, 255, 255));
        panel_drive.setLayout(new javax.swing.BoxLayout(panel_drive, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane2.setViewportView(panel_drive);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        bt_Folder.setText("jButton1");
        bt_Folder.setContentAreaFilled(false);
        bt_Folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_FolderActionPerformed(evt);
            }
        });

        bt_add.setBackground(new java.awt.Color(204, 51, 255));
        bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt1.PNG"))); // NOI18N
        bt_add.setContentAreaFilled(false);
        bt_add.setMaximumSize(new java.awt.Dimension(70, 70));
        bt_add.setMinimumSize(new java.awt.Dimension(60, 60));
        bt_add.setPreferredSize(new java.awt.Dimension(60, 60));
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addComponent(bt_Folder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Folder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void actualizar(){
        Node aux = (Node) actual_node.getFirstChild();
        panel_drive.removeAll();
        while(aux!=null){
            panel_drive.add(aux.icon);
            aux = (Node) aux.getNextSibling();
        }
        panel_drive.updateUI();
    }
    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        Node newNode = new Node(socket_salida.enviar(), true);
        newNode.icon.setIcon(btIfile);
        newNode.icon.addActionListener((ActionEvent evtb) -> {
            
        });
        actual_node.add(newNode);
        file_tree.setModel(new DefaultTreeModel(raiz));
        actualizar();
        
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_FolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_FolderActionPerformed
        // TODO add your handling code here:
        Node newNode = new Node(JOptionPane.showInputDialog(null,"Nueva carpeta"), true);
        Node regresar = new Node("...", true);
        regresar.icon.setIcon(btIfolder);
        newNode.icon.setIcon(btIfolder);
        newNode.add(regresar);
        newNode.icon.addActionListener((ActionEvent evtb) -> {
            actual_node = newNode;
            actualizar();
        });
        regresar.icon.addActionListener((ActionEvent evtb) -> {
            actual_node = (Node)newNode.getParent();
            actualizar();
        });
        actual_node.add(newNode);
        file_tree.setModel(new DefaultTreeModel(raiz));
        actualizar();
        
    }//GEN-LAST:event_bt_FolderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Folder;
    private javax.swing.JButton bt_add;
    private javax.swing.JTree file_tree;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_drive;
    // End of variables declaration//GEN-END:variables
}
